version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Auto-update tools dependencies, but not library dependencies.
  - package-ecosystem: "gomod"
    directory: "/tools"
    schedule:
      interval: "weekly"
