# Use this file to configure the Overcommit hooks you wish to use. This will
# extend the default configuration defined in:
# https://github.com/brigade/overcommit/blob/master/config/default.yml
#
# For a complete list of hooks, see:
# https://github.com/brigade/overcommit/tree/master/lib/overcommit/hook
#
# For a complete list of options that you can use to customize hooks, see:
# https://github.com/brigade/overcommit#configuration
#

CommitMsg:
  HardTabs:
    enabled: true

  TextWidth:
    enabled: true
    max_subject_width: 60
    on_warn: fail

PreCommit:
  GoVet:
    enabled: true

  LicenceHeader:
    enabled: true
    include:
      - '**/*.go'

  # Markdown lint
  Mdl:
    enabled: true

  ShellCheck:
    enabled: true

  TrailingWhitespace:
    enabled: true

  JsonSyntax:
    enabled: true

  YamlSyntax:
    enabled: true

  ExecutePermissions:
    enabled: true
    exclude:
      - '.bin/*.sh'

#PostCheckout:
#  ALL: # Special hook name that customizes all hooks of this type
#    quiet: true # Change all post-checkout hooks to only display output on failure
#
#  IndexTags:
#    enabled: true # Generate a tags file with `ctags` each time HEAD changes
