sudo: required
services:
  - docker
env:
  - DOCKER_GO_VERSION=1.7 V=1 COVERMODE=atomic
  - DOCKER_GO_VERSION=1.8 V=1 COVERMODE=atomic
matrix:
  fast_finish: true
before_install:
  - make dockerbuild
script:
  - make dockerrun DOCKER_MAKE_CMD=ci
after_success:
   - '[ "${TRAVIS_GO_VERSION}" == "1.8" ] && make dockerrun DOCKER_MAKE_CMD=coveralls'
