sudo: false
language: go
go_import_path: go.uber.org/fx

env:
  global:
    - GO111MODULE=on

matrix:
  include:
  - go: stable
    env: LINT=1
  - go: oldstable

install:
  - make install

script:
  - test -z "$LINT" || make lint
  - make test

after_success:
  - make cover
  - bash <(curl -s https://codecov.io/bash)
