language: go
sudo: false
go:
  - 1.7
  - 1.8
  # TODO(aiden) re-enable tip once "gimme tip" works in travis again

go_import_path: go.uber.org/fx

env:
  - V=1 COVERMODE=atomic

matrix:
  # Fail the build as soon as the first job fails
  fast_finish: true

cache:
  directories:
    - vendor

install:
  - make deps

script:
  - make lint
  - make test

after_success:
   - '[ "${TRAVIS_GO_VERSION}" == "1.8" ] && make coveralls'
