sudo: required
services:
  - docker
cache:
  directories:
    - .cache/docker
env:
  - DOCKER_GO_VERSION=1.9
  - DOCKER_GO_VERSION=1.10 CI_TEST_CMD=coveralls
before_install:
  - make dockerload
script:
  - make dockerci
  - if [[ "${TRAVIS_BRANCH}" == "master" ]] && [[ "${TRAVIS_PULL_REQUEST}" == "false" ]]; then make dockersave; fi
