applicationID: simple
applicationDesc: A simple example service
applicationOwner: owner@service.com

service:
  timeout: 500
  max_things: 12
  info_prefix: blah

modules:
  http:
    roles:
      - worker
      - web
    port: 8080
  kafka:
    roles: worker
    zk: http://zk/1234
