logging:
  stdout: true
  level: info
  encoder: json

yarpc:
  name: noo
  inbounds:
    - tchannel:
        port: 1234
  outbounds:
    - service: noo
      tchannel:
        host: 127.0.0.1
        port: 1234
