name: FOSSA Analysis
on: push

jobs:

  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'uber-go'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: FOSSA analysis
        uses: fossas/fossa-action@v1
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}

permissions:
  contents: read
